# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
unsetopt beep
# End of lines configured by zsh-newuser-install

# file generated by running compinstall
. /home/kamil/.zsh_completions

# for `zoxide` to work (smarted `cd` command: `z`)
eval "$(zoxide init zsh)"

# rebind caps lock to ctrl
# for now this is achieved by running: `localectl set-x11-keymap "pl" "" "" "ctrl:swapcaps"`
# setxkbmap -layout pl -option ctrl:nocaps

# To share history between all zsh sessions immediately (and in effect share it between tmux panes)
# note: you have to hit enter at least once so the current pane will pick up entries inputted in the other
setopt INC_APPEND_HISTORY

# To ignore commands starting with space from history. The command lingers in the internal history until the next
# command is entered before it vanishes, allowing to briefly reuse or edit the line.
setopt HIST_IGNORE_SPACE
# To ignore patterns from history (not a regex):
HISTORY_IGNORE="git checkout -b '*"

# Speed up your keyboard - mostly to make stuff scroll faster
# xset r rate 150 45

# due to some weird bug, tmuxp won't run without this:
# https://github.com/tmux-python/tmuxp/issues/405
# source ~/.bash_locale

# To unbind ctrl-s (ctrl-s more or less just freezes the terminal, its a redundant functionality from ancient times).
# Thanks to this we can bind ctrl-s to something useful, like 'exit nvim terminal insert mode' for example.
setopt noflowcontrol

# vi mode
bindkey -e
export KEYTIMEOUT=1

# Edit line in vim with ctrl-e:
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

# here goes prompt customization:
#
# Load version control information
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
autoload -Uz vcs_info
precmd() { vcs_info }

# Allow usage of "%u" in git formats (check for unstaged changes)
zstyle ':vcs_info:*' check-for-changes true

# Format the vcs_info_msg_0_ variable
# %b - branch name
# %u - indicate unstaged changes
# %c - indicate staged changes
# %a - indicate git action going on, like merge/rebase
# To change default string, i.e. for %u
# zstyle ':vcs_info:*' unstagedstr '*'

zstyle ':vcs_info:git:*' formats '%b %u%c %a'

# Set up the prompt
# vcs_info_msg_0_ - git info
setopt PROMPT_SUBST
PROMPT='
%B%F{67}${PWD/#$HOME/~}%f%b %F{243}${vcs_info_msg_0_}%f
%B%F{96}> %f%b'
# end of prompt customization

# ASDF (version manager) related
# https://github.com/asdf-vm/asdf
# https://asdf-vm.com/#/core-manage-asdf
. $HOME/.asdf/asdf.sh

# FZF (fuzzy search) related
# To follow symbolic link and don't exclude hidden files (except .git dir). Use find alternative - fd.
export FZF_DEFAULT_COMMAND='fd --no-ignore --type f --hidden --follow --exclude .git'
# enable terminal shortcuts, for example <ctrl>+R to search through terminal history
source /usr/share/fzf/key-bindings.zsh
# enable <tab> commands completions, for example kill <tab>
source /usr/share/fzf/completion.zsh

# Load zsh-syntax-highlighting; should be last. Require 'zsh-syntax-highlighting' package installed to work
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh 2>/dev/null

# Load zsh-autosuggestions. Require `git clone https://github.com/zsh-users/zsh-autosuggestions ~/.zsh/zsh-autosuggestions` to work
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh
# bind ctrl + space to accept the current suggestion:
bindkey '^ ' autosuggest-accept

# This is to cache ssh passwords, so that user is being asked only first time for it (for example when operating git)
# There is also corresponding config under ~/.ssh/config (AddKeysToAgent)
# REFERENCE: https://wiki.archlinux.org/title/SSH_keys#Start_ssh-agent_with_systemd_user
export SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket

screen-capture-region() {
  grim -g "$(slurp)" - | swappy -f -
}
screen-record-region() {
  wf-recorder -g "$(slurp)" -f ~/Videos/screen-recording-capture/recording.mp4
}
screen-record() {
  wf-recorder
}
remove-from-shell-history() {
  selected=$(fzf < "/home/kamil/.histfile") && pattern=$(printf '%q' "$selected") && sed -i "/^$pattern$/d" "/home/kamil/.histfile"
}
