# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=10000
SAVEHIST=10000
unsetopt beep
# End of lines configured by zsh-newuser-install

# file generated by running compinstall
. /home/kamil/.zsh_completions

# rebindd caps lock to ctrl
# for now this is achieved by running: `localectl set-x11-keymap "pl" "" "" "ctrl:swapcaps"`
# setxkbmap -layout pl -option ctrl:nocaps

# Speed up your keyboard - mostly to make stuff scroll faster
xset r rate 200 40

# due to some weird bug, tmuxp won't run without this:
# https://github.com/tmux-python/tmuxp/issues/405
source ~/.bash_locale

# here goes prompt customization:
#
# Load version control information
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
autoload -Uz vcs_info
precmd() { vcs_info }

# Allow usage of "%u" in git formats (check for unstaged changes)
zstyle ':vcs_info:*' check-for-changes true

# Format the vcs_info_msg_0_ variable
# %b - branch name
# %u - indicate unstaged changes
# %c - indicate staged changes
# %a - indicate git action going on, like merge/rebase
# To change default string, i.e. for %u
# zstyle ':vcs_info:*' unstagedstr '*'

zstyle ':vcs_info:git:*' formats '%b %u%c %a'

# Set up the prompt
# vcs_info_msg_0_ - git info
setopt PROMPT_SUBST
PROMPT='
%B%F{67}${PWD/#$HOME/~}%f%b %F{243}${vcs_info_msg_0_}%f
%B%F{96}> %f%b'
# end of prompt customization

# ASDF (version manager) related
# https://github.com/asdf-vm/asdf
# https://asdf-vm.com/#/core-manage-asdf
. $HOME/.asdf/asdf.sh

# FZF (fuzy search) related 
# To follow symbolic link and don't exclude hidden files (except .git dir). Use find alternative - fd.
export FZF_DEFAULT_COMMAND='fd --no-ignore --type f --hidden --follow --exclude .git'
# enable terminal shortcuts, for example <ctrl>+R to search through terminal history
source /usr/share/fzf/key-bindings.zsh
# enable <tab> commands completions, for example kill <tab>
source /usr/share/fzf/completion.zsh

