# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=10000
unsetopt beep
# End of lines configured by zsh-newuser-install

# Unitrak custom config:

# file generated by running compinstall
. /home/kamil/.zsh_completions

# form ctrl+a and ctrl+e to work (jump to beginning/end of the line)
bindkey -e

# due to some wierd bug, tmuxp won't run without this:
# https://github.com/tmux-python/tmuxp/issues/405
source ~/.bash_locale

# here goes prompt customization:
#
# Load version control information
# http://zsh.sourceforge.net/Doc/Release/User-Contributions.html#Version-Control-Information
autoload -Uz vcs_info
precmd() { vcs_info }

# Allow usage of "%u" in git formats (check for unstaged changes)
zstyle ':vcs_info:*' check-for-changes true

# Format the vcs_info_msg_0_ variable
# %b - branch name
# %u - indicate unstaged changes
# %c - indicate staged changes
# %a - indicate git action going on, like merge/rebase
# To change default string, i.e. for %u
# zstyle ':vcs_info:*' unstagedstr '*'

zstyle ':vcs_info:git:*' formats '%b %u%c %a'

# Set up the prompt
# vcs_info_msg_0_ - git info
setopt PROMPT_SUBST
PROMPT='
%B%F{67}${PWD/#$HOME/~}%f%b %F{243}${vcs_info_msg_0_}%f
%B%F{96}> %f%b'
# end of prompt customization

# asdf version manager config
# https://github.com/asdf-vm/asdf
# https://asdf-vm.com/#/core-manage-asdf
. $HOME/.asdf/asdf.sh

# General aliases
alias ls='ls --color=auto'
alias grep='grep --color'
alias notes_status="(cd ~/Work/notes && git status && git diff)"
alias notes_save="(cd ~/Work/notes && git pull && git add . && git commit -m 'save point' && git push)"
alias dotfiles_save="(cd ~/Misc/dotfiles && git pull && git add . && git commit -m 'save point' && git push)"
alias g="git"
# ruby/rails
alias be="bundle exec"
alias ber="bundle exec rspec"
alias besr="bundle exec spring rspec"
alias berf="bundle exec rspec --only-failures"
alias bec="bundle exec rails console"
alias bes="bundle exec rails server"
alias beg="bundle exec rails generate"
alias bek="bundle exec rake"
alias rubo="bundle exec rubocop --auto-correct"
dbregen() {
  bin/rails db:environment:set RAILS_ENV=test
  bundle exec rake db:drop db:create db:migrate RAILS_ENV=test
}
# tap speciffic aliases
alias tap_workspace="sh ~/Misc/dotfiles/system_workspaces/tap.sh"
alias tap_qa="bundle exec cap qa rails:console"
tap_current_specs() {
  rm -f spec/examples.txt
  ber spec/concepts/form/**/* \
    spec/concepts/form_group/**/* \
    spec/concepts/form_module_value/**/* \
    spec/concepts/form_formula_template/**/* \
    spec/concepts/form_element/**/* \
    spec/concepts/form_run/**/* \
    spec/concepts/element_group_item/**/* \
    spec/concepts/element/**/* \
    spec/requests/api/v2/forms/**/* \
    spec/requests/api/v2/form_runs/**/* \
    spec/requests/api/v2/element_group_items/**/* \
    spec/requests/api/v2/elements/**/* \
    spec/models/form_*_spec.rb \
    spec/models/form_spec.rb \
    spec/models/element_spec.rb \
    spec/models/element_group_item_spec.rb \
    spec/db/deployment/v5.14_spec.rb
}






